// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_yc65mHLVVoaD_I1-fLG03i3TOw2U3_o',
    appId: '1:943452458673:web:645899be4b756d0ed85c90',
    messagingSenderId: '943452458673',
    projectId: 'final-crud09',
    authDomain: 'final-crud09.firebaseapp.com',
    storageBucket: 'final-crud09.appspot.com',
    measurementId: 'G-SP76WJKWDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaZ3e5ZigHPnuRiaAZFIvmIhlDzuDH1dc',
    appId: '1:943452458673:android:2cc09e05f51ce78dd85c90',
    messagingSenderId: '943452458673',
    projectId: 'final-crud09',
    storageBucket: 'final-crud09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz8tb2MRrGNHP_m9IQvXYCWn63-5vCc64',
    appId: '1:943452458673:ios:6c590b5db4cfd26dd85c90',
    messagingSenderId: '943452458673',
    projectId: 'final-crud09',
    storageBucket: 'final-crud09.appspot.com',
    iosBundleId: 'com.example.naofacoideia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz8tb2MRrGNHP_m9IQvXYCWn63-5vCc64',
    appId: '1:943452458673:ios:6c590b5db4cfd26dd85c90',
    messagingSenderId: '943452458673',
    projectId: 'final-crud09',
    storageBucket: 'final-crud09.appspot.com',
    iosBundleId: 'com.example.naofacoideia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_yc65mHLVVoaD_I1-fLG03i3TOw2U3_o',
    appId: '1:943452458673:web:1be75b3cd6e583c9d85c90',
    messagingSenderId: '943452458673',
    projectId: 'final-crud09',
    authDomain: 'final-crud09.firebaseapp.com',
    storageBucket: 'final-crud09.appspot.com',
    measurementId: 'G-D0P1M00DQ2',
  );
}
